version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
<<<<<<< HEAD

on:
  push:
    # déclenche sur main OU principal (sécurise)
    branches: [ 'main', 'principal' ]
  pull_request:
    branches: [ 'main', 'principal' ]
  # Permet d'exécuter manuellement depuis l'UI
  workflow_dispatch:
=======
    allow:
      - dependency-type: "direct"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "chore(deps):"
>>>>>>> 6eb8a4e (chore(ci): harmonisation des workflows Python, sécurité et templates)
