name: CI Pipeline (Python)

on:
  push:
    branches: [ 'main', 'principal' ]
  pull_request:
    branches: [ 'main', 'principal' ]
  workflow_dispatch:

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.10, 3.11]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m venv .venv
          source .venv/bin/activate
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Lint (optional)
        run: |
          source .venv/bin/activate
          # Run linter if present (ruff/flake8)
          if command -v ruff >/dev/null 2>&1; then ruff check . || true; fi

      - name: Run tests
        run: |
          source .venv/bin/activate
          pytest -q
