name: CI — Lint & Tests (Python)

on:
  push:
    branches: ["main", "principal"]
  pull_request:
    branches: ["main", "principal"]
  workflow_dispatch:

jobs:
  lint-and-test:
    name: Lint and Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.12, 3.11, 3.10]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ matrix.python-version }}-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-${{ matrix.python-version }}-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Format check (black)
        run: |
          python -m black --version || true
          python -m black --check .
        continue-on-error: false

      - name: Import sort check (isort)
        run: |
          python -m isort --version || true
          python -m isort --check-only .

      - name: Lint (flake8)
        run: |
          python -m flake8 || true

      - name: Run tests (pytest)
        run: |
          python -m pytest -q
