name: Security Scan

on:
  push:
    # déclenche sur main OU principal (sécurise)
    branches: [ 'main', 'principal' ]
  pull_request:
    branches: [ 'main', 'principal' ]
  # Permet d'exécuter manuellement depuis l'UI
  workflow_dispatch:
  schedule:
    - cron: "0 2 * * 1" # tous les lundis à 2h UTC

jobs:
  codeql:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      actions: read
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: javascript

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3
