name: Security — Code scanning & dependency checks

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: "0 2 * * 1" # every Monday at 02:00 UTC

permissions:
  contents: read
  security-events: write

jobs:
  codeql:
    name: CodeQL analysis (Python)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: python

      - name: Autobuild (pip)
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3

  dependency-scan:
    name: Safety dependency scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install safety
        run: python -m pip install --upgrade pip safety

      - name: Run safety
        run: |
          if [ -f requirements.txt ]; then safety check --full-report -r requirements.txt || true; else echo "No requirements.txt found"; fi
