name: Security Scan (CodeQL)

on:
  push:
    branches: [ 'main', 'principal' ]
  pull_request:
    branches: [ 'main', 'principal' ]
  schedule:
    - cron: "0 3 * * 1"
  workflow_dispatch:

jobs:
  codeql:
    name: codeql-analysis
    permissions:
      actions: read
      contents: read
      security-events: write
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: python

      - name: Autobuild (optional)
        uses: github/codeql-action/autobuild@v3

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3
